CREATE OR REFRESH STREAMING TABLE ECOMMERCE.GOLD.CUSTOMERS_SCD1
TBLPROPERTIES ('quality' = 'silver');

APPLY CHANGES INTO LIVE.CUSTOMERS_SCD1
FROM STREAM(LIVE.ECOMMERCE.SILVER.ORDERS_ENRICHED)
KEYS (customer_id)
SEQUENCE BY created_timestamp
STORED AS SCD TYPE 1;