CREATE OR REFRESH STREAMING TABLE ECOMMERCE.SILVER.CUSTOMERS_SCD1
TBLPROPERTIES ('quality' = 'silver');

APPLY CHANGES INTO ECOMMERCE.SILVER.CUSTOMERS_SCD1
FROM STREAM(LIVE.ECOMMERCE.SILVER.CUSTOMERS_ENRICHED)
KEYS (customer_id)
SEQUENCE BY created_date
STORED AS SCD TYPE 1;