CREATE OR REFRESH STREAMING TABLE CIRCUIT.SILVER.CUSTOMERS_SCD1
TBLPROPERTIES ('quality' = 'silver');

APPLY CHANGES INTO CIRCUIT.SILVER.CUSTOMERS_SCD1
FROM STREAM(LIVE.CIRCUIT.SILVER.CUSTOMERS_ENRICHED)
KEYS (customer_id)
SEQUENCE BY created_date
STORED AS SCD TYPE 1;